apiVersion: apps/v1
kind: Deployment
metadata:
  name: kube-deployment
  labels:
    app: kube
spec:
  replicas: 3
  selector:
    matchLabels:
      app: kube
  template:
    metadata:
      labels:
        app: kube
    spec:
      containers:
      - name: kube
        image: nginx:1.14.2
        ports:
        - containerPort: 80